/**
 * NASA Astronomy Picture of the Day (APOD) Plugin for TRMNL Dashboard
 * Fetches the daily featured space picture and details from api.nasa.gov.
 * Employs local caching to make exactly one API request per day to prevent rate limit issues.
 */

(function() {
  'use strict';

  var NASAPhotoPlugin = {
    id: 'nasa_space_photo',
    name: 'NASA Space Photo',
    config: {},
    container: null,

    init: function(pluginConfig) {
      this.config = pluginConfig || {};
    },

    render: function(element) {
      this.container = element;
      this.fetchNASAPhoto();
    },

    update: function() {
      this.fetchNASAPhoto();
    },

    fetchNASAPhoto: function() {
      if (!this.container) return;

      var self = this;
      var today = new Date().toDateString();

      // Check cache first
      try {
        var cached = localStorage.getItem('trmnl_nasa_apod');
        if (cached) {
          var parsed = JSON.parse(cached);
          if (parsed && parsed.dateStr === today && parsed.data && parsed.data.url) {
            self.drawPhoto(parsed.data);
            return;
          }
        }
      } catch (e) {
        console.warn("Failed to read APOD cache:", e);
      }

      if (navigator.onLine) {
        self.drawLoading();
        
        var url = "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&thumbs=true";
        
        fetch(url)
          .then(function(res) {
            if (!res.ok) throw new Error("HTTP error " + res.status);
            return res.json();
          })
          .then(function(data) {
            if (data && (data.url || data.thumbnail_url)) {
              var imgUrl = data.url;
              // If it's a video, use the thumbnail generated by NASA
              if (data.media_type === 'video' && data.thumbnail_url) {
                imgUrl = data.thumbnail_url;
              }

              var photoData = {
                url: imgUrl,
                title: data.title || "Astronomy Picture of the Day",
                copyright: data.copyright ? data.copyright.replace(/\n/g, ' ').trim() : "NASA public domain"
              };

              // Cache the result
              try {
                var cacheObj = {
                  dateStr: today,
                  data: photoData
                };
                localStorage.setItem('trmnl_nasa_apod', JSON.stringify(cacheObj));
              } catch (e) {
                console.warn("Failed to write APOD cache:", e);
              }

              self.drawPhoto(photoData);
            } else {
              throw new Error("Invalid APOD response");
            }
          })
          .catch(function(err) {
            console.error("NASA APOD fetch failed:", err);
            self.drawError(err.message);
          });
      } else {
        // Try to fall back to whatever is in cache even if it's from a previous day
        try {
          var cachedFallback = localStorage.getItem('trmnl_nasa_apod');
          if (cachedFallback) {
            var parsedFallback = JSON.parse(cachedFallback);
            if (parsedFallback && parsedFallback.data) {
              self.drawPhoto(parsedFallback.data);
              return;
            }
          }
        } catch (e) {}
        
        self.drawOffline();
      }
    },

    drawPhoto: function(photoData) {
      this.currentPhoto = photoData;

      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">';
      
      // Main Card Content (Full-bleed card, padding 0)
      html += '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; padding: 0; margin-bottom: 16px; min-height: 480px; overflow: hidden; position: relative;">';
      html += '    <img src="' + photoData.url + '" alt="NASA APOD" style="width: 100%; height: 100%; object-fit: cover; filter: grayscale(1) contrast(1.35) brightness(0.9); image-rendering: auto;" decoding="async">';
      html += '    <div class="trmnl-dither" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; opacity: 0.35; pointer-events: none; mix-blend-mode: multiply;"></div>';
      html += '  </div>';

      var caption = photoData.title.toUpperCase();
      if (caption.length > 42) {
        caption = caption.substring(0, 39) + "...";
      }

      // Dithered Footer Bar
      html += '  <div class="trmnl-footer-bar">';
      html += '    <div class="trmnl-footer-badge">';
      // Telescope/Globe SVG Icon
      html += '      <svg viewBox="0 0 24 24" style="width:14px;height:14px;fill:none;stroke:var(--text-color);stroke-width:2.5;vertical-align:middle;flex-shrink:0;"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>';
      html += '      <span>NASA Space Photo</span>';
      html += '    </div>';
      html += '    <div class="trmnl-footer-meta" style="display:flex; align-items:center; gap:8px;">';
      html += '      <span>' + caption + '</span>';
      html += '      <span id="nasa-set-wp-btn" style="cursor:pointer; text-decoration:underline; font-size:10px; opacity:0.8; font-weight:700; font-family:var(--font-mono); letter-spacing:0.05em; display:inline-block; padding: 2px 4px;">[SET AS WALLPAPER]</span>';
      html += '    </div>';
      html += '  </div>';

      html += '</div>';

      this.container.innerHTML = html;
      this.bindEvents();
    },

    bindEvents: function() {
      if (!this.container) return;
      var self = this;
      var btn = this.container.querySelector('#nasa-set-wp-btn');
      if (btn) {
        btn.addEventListener('click', function(e) {
          e.stopPropagation();
          self.saveAsWallpaper();
        });
        btn.addEventListener('touchstart', function(e) {
          e.stopPropagation();
        });
      }
    },

    saveAsWallpaper: function() {
      var photo = this.currentPhoto;
      if (!photo || !photo.url) return;

      var self = this;
      var btn = this.container.querySelector('#nasa-set-wp-btn');
      if (btn) {
        btn.textContent = '[SAVING...]';
        btn.style.pointerEvents = 'none';
        btn.style.opacity = '0.5';
      }

      // Format clean date ID
      var dateId = new Date().toISOString().split('T')[0]; // e.g. "2026-06-11"
      var wallpaperId = 'nasa-' + dateId;

      function urlToBase64(url, callback) {
        var img = new Image();
        img.crossOrigin = 'Anonymous';
        img.onload = function() {
          var maxWidth = 1024;
          var maxHeight = 768;
          var width = img.width;
          var height = img.height;
          
          if (width > height) {
            if (width > maxWidth) {
              height = Math.round(height * (maxWidth / width));
              width = maxWidth;
            }
          } else {
            if (height > maxHeight) {
              width = Math.round(width * (maxHeight / height));
              height = maxHeight;
            }
          }
          
          var canvas = document.createElement('canvas');
          canvas.width = width;
          canvas.height = height;
          var ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0, width, height);
          try {
            var dataURL = canvas.toDataURL('image/jpeg', 0.75);
            callback(null, dataURL);
          } catch (e) {
            callback(e, null);
          }
        };
        img.onerror = function(err) {
          callback(err, null);
        };
        img.src = url;
      }

      urlToBase64(photo.url, function(err, base64Data) {
        if (err) {
          console.warn("Could not convert NASA APOD image to Base64 (CORS/network):", err);
        }

        var savedList = [];
        try {
          var cachedSaved = localStorage.getItem('trmnl_nasa_saved_wallpapers');
          if (cachedSaved) savedList = JSON.parse(cachedSaved);
        } catch (e) {}

        if (!Array.isArray(savedList)) {
          savedList = [];
        }

        // Filter out any existing duplicate ID
        savedList = savedList.filter(function(item) {
          return item && item.id !== wallpaperId;
        });

        var name = 'NASA ' + dateId + ' - ' + photo.title;
        if (name.length > 42) {
          name = 'NASA ' + dateId;
        }

        var newEntry = {
          id: wallpaperId,
          name: name,
          url: photo.url,
          base64: base64Data || null,
          date: dateId
        };

        savedList.unshift(newEntry);

        // Save back to localStorage
        try {
          localStorage.setItem('trmnl_nasa_saved_wallpapers', JSON.stringify(savedList));
        } catch(e) {
          console.warn("Failed to save NASA wallpaper list:", e);
        }

        // Update active configuration
        var settings = {};
        try {
          var cachedSettings = localStorage.getItem('trmnl_dashboard_settings');
          if (cachedSettings) settings = JSON.parse(cachedSettings);
        } catch(e) {}

        settings.wallpaper = wallpaperId;
        settings.wallpaperDark = null;

        try {
          localStorage.setItem('trmnl_dashboard_settings', JSON.stringify(settings));
        } catch(e) {
          console.warn("Failed to persist dashboard settings:", e);
        }

        // Restore button state with success feedback
        if (btn) {
          btn.textContent = '[SET!]';
          btn.style.color = '#00aa00';
          btn.style.pointerEvents = 'auto';
          btn.style.opacity = '1';
          setTimeout(function() {
            btn.textContent = '[SET AS WALLPAPER]';
            btn.style.color = '';
          }, 2000);
        }

        // Trigger settings reload to apply changes immediately
        if (window.Dashboard && typeof window.Dashboard.reloadSettings === 'function') {
          window.Dashboard.reloadSettings();
        }
      });
    },

    drawLoading: function() {
      if (!this.container) return;
      this.container.innerHTML =
        '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
        '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:32px; margin-bottom:16px;">' +
        '    <div style="font-family:var(--font-mono); font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:0.06em; opacity:0.55; margin-bottom:12px;">Contacting NASA...</div>' +
        '    <div style="font-family:var(--font-sans); font-size:24px; font-weight:700;">Loading Space Photo</div>' +
        '  </div>' +
        '  <div class="trmnl-footer-bar">' +
        '    <div class="trmnl-footer-badge">' +
        '      <span>NASA Space Photo</span>' +
        '    </div>' +
        '    <div class="trmnl-footer-meta">CONNECTING...</div>' +
        '  </div>' +
        '</div>';
    },

    drawError: function(msg) {
      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
                 '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding: 32px; margin-bottom: 16px;">' +
                 '    <svg style="width:48px; height:48px; stroke:var(--text-color); stroke-width:2; fill:none; margin-bottom:16px;" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>' +
                 '    <div style="font-family: var(--font-sans); font-size: 18px; font-weight:700;">Failed to load NASA APOD</div>' +
                 '    <div style="font-family: var(--font-mono); font-size: 11px; opacity:0.6; margin-top:8px; text-align:center; max-width:360px;">' + (msg || "Check network connection") + '</div>' +
                 '  </div>' +
                 '  <div class="trmnl-footer-bar">' +
                 '    <div class="trmnl-footer-badge">' +
                 '      <span>NASA Space Photo</span>' +
                 '    </div>' +
                 '    <div class="trmnl-footer-meta">NASA API ERROR</div>' +
                 '  </div>' +
                 '</div>';
      this.container.innerHTML = html;
    },

    drawOffline: function() {
      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
                 '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding: 32px; margin-bottom: 16px;">' +
                 '    <svg style="width:48px; height:48px; stroke:var(--text-color); stroke-width:2; fill:none; margin-bottom:16px;" viewBox="0 0 24 24"><path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.5M5 12.5a10.94 10.94 0 0 1 5.83-2.84M8.5 16.5a10.94 10.94 0 0 1 3.5-1.5M12 18.5a10.94 10.94 0 0 1 0-3.5M15.5 16.5a10.94 10.94 0 0 1-3.5-1.5"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>' +
                 '    <div style="font-family: var(--font-sans); font-size: 18px; font-weight:700;">Offline Mode</div>' +
                 '    <div style="font-family: var(--font-mono); font-size: 12px; opacity:0.6; margin-top:8px;">NASA Space Photo requires active network</div>' +
                 '  </div>' +
                 '  <div class="trmnl-footer-bar">' +
                 '    <div class="trmnl-footer-badge">' +
                 '      <span>NASA Space Photo</span>' +
                 '    </div>' +
                 '    <div class="trmnl-footer-meta">OFFLINE</div>' +
                 '  </div>' +
                 '</div>';
      this.container.innerHTML = html;
    }
  };

  // Register plugin
  window.Plugins = window.Plugins || {};
  window.Plugins.nasa_space_photo = NASAPhotoPlugin;

})();
