/**
 * NASA Astronomy Picture of the Day (APOD) Plugin for TRMNL Dashboard
 * Fetches the daily featured space picture and details from api.nasa.gov.
 * Employs local caching to make exactly one API request per day to prevent rate limit issues.
 */

(function() {
  'use strict';

  var NASAPhotoPlugin = {
    id: 'wikiphoto',
    name: 'Space Photo',
    config: {},
    container: null,

    init: function(pluginConfig) {
      this.config = pluginConfig || {};
    },

    render: function(element) {
      this.container = element;
      this.fetchNASAPhoto();
    },

    update: function() {
      this.fetchNASAPhoto();
    },

    fetchNASAPhoto: function() {
      if (!this.container) return;

      var self = this;
      var today = new Date().toDateString();

      // Check cache first
      try {
        var cached = localStorage.getItem('trmnl_nasa_apod');
        if (cached) {
          var parsed = JSON.parse(cached);
          if (parsed && parsed.dateStr === today && parsed.data && parsed.data.url) {
            self.drawPhoto(parsed.data);
            return;
          }
        }
      } catch (e) {
        console.warn("Failed to read APOD cache:", e);
      }

      if (navigator.onLine) {
        self.drawLoading();
        
        var url = "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&thumbs=true";
        
        fetch(url)
          .then(function(res) {
            if (!res.ok) throw new Error("HTTP error " + res.status);
            return res.json();
          })
          .then(function(data) {
            if (data && (data.url || data.thumbnail_url)) {
              var imgUrl = data.url;
              // If it's a video, use the thumbnail generated by NASA
              if (data.media_type === 'video' && data.thumbnail_url) {
                imgUrl = data.thumbnail_url;
              }

              var photoData = {
                url: imgUrl,
                title: data.title || "Astronomy Picture of the Day",
                copyright: data.copyright ? data.copyright.replace(/\n/g, ' ').trim() : "NASA public domain"
              };

              // Cache the result
              try {
                var cacheObj = {
                  dateStr: today,
                  data: photoData
                };
                localStorage.setItem('trmnl_nasa_apod', JSON.stringify(cacheObj));
              } catch (e) {
                console.warn("Failed to write APOD cache:", e);
              }

              self.drawPhoto(photoData);
            } else {
              throw new Error("Invalid APOD response");
            }
          })
          .catch(function(err) {
            console.error("NASA APOD fetch failed:", err);
            self.drawError(err.message);
          });
      } else {
        // Try to fall back to whatever is in cache even if it's from a previous day
        try {
          var cachedFallback = localStorage.getItem('trmnl_nasa_apod');
          if (cachedFallback) {
            var parsedFallback = JSON.parse(cachedFallback);
            if (parsedFallback && parsedFallback.data) {
              self.drawPhoto(parsedFallback.data);
              return;
            }
          }
        } catch (e) {}
        
        self.drawOffline();
      }
    },

    drawPhoto: function(photoData) {
      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">';
      
      // Main Card Content (Full-bleed card, padding 0)
      html += '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; padding: 0; margin-bottom: 16px; min-height: 480px; overflow: hidden; position: relative;">';
      html += '    <img src="' + photoData.url + '" alt="NASA APOD" style="width: 100%; height: 100%; object-fit: cover; filter: grayscale(1) contrast(1.35) brightness(0.9); image-rendering: auto;">';
      html += '    <div class="trmnl-dither" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; opacity: 0.35; pointer-events: none; mix-blend-mode: multiply;"></div>';
      html += '  </div>';

      var caption = photoData.title.toUpperCase();
      if (caption.length > 42) {
        caption = caption.substring(0, 39) + "...";
      }

      // Dithered Footer Bar
      html += '  <div class="trmnl-footer-bar">';
      html += '    <div class="trmnl-footer-badge">';
      // Telescope/Globe SVG Icon
      html += '      <svg viewBox="0 0 24 24" style="width:14px;height:14px;fill:none;stroke:var(--text-color);stroke-width:2.5;vertical-align:middle;flex-shrink:0;"><circle cx="12" cy="12" r="10"></circle><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path><path d="M2 12h20"></path></svg>';
      html += '      <span>NASA Space Photo</span>';
      html += '    </div>';
      html += '    <div class="trmnl-footer-meta">' + caption + '</div>';
      html += '  </div>';

      html += '</div>';

      this.container.innerHTML = html;
    },

    drawLoading: function() {
      if (!this.container) return;
      this.container.innerHTML =
        '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
        '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:32px; margin-bottom:16px;">' +
        '    <div style="font-family:var(--font-mono); font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:0.06em; opacity:0.55; margin-bottom:12px;">Contacting NASA...</div>' +
        '    <div style="font-family:var(--font-sans); font-size:24px; font-weight:700;">Loading Space Photo</div>' +
        '  </div>' +
        '  <div class="trmnl-footer-bar">' +
        '    <div class="trmnl-footer-badge">' +
        '      <span>NASA Space Photo</span>' +
        '    </div>' +
        '    <div class="trmnl-footer-meta">CONNECTING...</div>' +
        '  </div>' +
        '</div>';
    },

    drawError: function(msg) {
      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
                 '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding: 32px; margin-bottom: 16px;">' +
                 '    <svg style="width:48px; height:48px; stroke:var(--text-color); stroke-width:2; fill:none; margin-bottom:16px;" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>' +
                 '    <div style="font-family: var(--font-sans); font-size: 18px; font-weight:700;">Failed to load NASA APOD</div>' +
                 '    <div style="font-family: var(--font-mono); font-size: 11px; opacity:0.6; margin-top:8px; text-align:center; max-width:360px;">' + (msg || "Check network connection") + '</div>' +
                 '  </div>' +
                 '  <div class="trmnl-footer-bar">' +
                 '    <div class="trmnl-footer-badge">' +
                 '      <span>NASA Space Photo</span>' +
                 '    </div>' +
                 '    <div class="trmnl-footer-meta">NASA API ERROR</div>' +
                 '  </div>' +
                 '</div>';
      this.container.innerHTML = html;
    },

    drawOffline: function() {
      var html = '<div style="display:flex; flex-direction:column; height:100%; justify-content:space-between; padding: 10px 0;">' +
                 '  <div class="trmnl-card" style="flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; padding: 32px; margin-bottom: 16px;">' +
                 '    <svg style="width:48px; height:48px; stroke:var(--text-color); stroke-width:2; fill:none; margin-bottom:16px;" viewBox="0 0 24 24"><path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.5M5 12.5a10.94 10.94 0 0 1 5.83-2.84M8.5 16.5a10.94 10.94 0 0 1 3.5-1.5M12 18.5a10.94 10.94 0 0 1 0-3.5M15.5 16.5a10.94 10.94 0 0 1-3.5-1.5"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>' +
                 '    <div style="font-family: var(--font-sans); font-size: 18px; font-weight:700;">Offline Mode</div>' +
                 '    <div style="font-family: var(--font-mono); font-size: 12px; opacity:0.6; margin-top:8px;">NASA Space Photo requires active network</div>' +
                 '  </div>' +
                 '  <div class="trmnl-footer-bar">' +
                 '    <div class="trmnl-footer-badge">' +
                 '      <span>NASA Space Photo</span>' +
                 '    </div>' +
                 '    <div class="trmnl-footer-meta">OFFLINE</div>' +
                 '  </div>' +
                 '</div>';
      this.container.innerHTML = html;
    }
  };

  // Register plugin
  window.Plugins = window.Plugins || {};
  window.Plugins.wikiphoto = NASAPhotoPlugin;

})();
